### ISSUE TITLE
Installation troubles and solutions

### ISSUE THREAD

**Issue by reloxx13** [nunofgs/rpi-octoprint#6]
Heya,

for everyone who got installation troubles of this docker imager, here is my exp so far:

pi 3b+ rasbian 

this is my docker run command:

take a note at the --device lines which is unclear in the readme.

```
#install OctoPrint
docker run -d  \
  --restart=unless-stopped \
  --name=OctoPrint \
  -p 1337:80 \
  --device=/dev/video0:/dev/video0 \
  --device=/dev/ttyUSB0:/dev/ttyUSB0 \
  -v /home/pi/Docker/OctoPrint/data:/data \
  -e STREAMER_FLAGS="-y -n -r 1280x720 -f 10" \
  nunofgs/octoprint:latest 
```

i use a logitech c920 webcam, you can get your STREAMER_FLAGS config from here:
https://github.com/foosel/OctoPrint/wiki/Webcams-known-to-work

Unfortunately the resolution is fixed in the supervisord.conf and the webcam ( mjpg_streamer ) is off by default.

orginal:

```
[program:mjpeg-streamer]
autostart=false
command=mjpg_streamer -i "/usr/local/lib/mjpg-streamer/input_uvc.so %(ENV_STREAMER_FLAGS)s -r 640x480 -d %(ENV_CAMERA_DEV)s" -o "/usr/local/lib/mjpg-streamer/output_http.so -w /usr/local/www -p 8080"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
```

to change that, i copied the https://github.com/nunofgs/docker-octoprint/blob/master/supervisord.conf into /home/pi/Docker/OctoPrint/data. than i added the autostart=true and removed the -r arg.
this is how it looks now:

```
 [program:mjpeg-streamer]
autostart=true
command=mjpg_streamer -i "/usr/local/lib/mjpg-streamer/input_uvc.so %(ENV_STREAMER_FLAGS)s -d %(ENV_CAMERA_DEV)s" -o "/usr/local/lib/mjpg-streamer/output_http.so -w /usr/local/www -p 8080"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
```

now i start the container with this:
`'/usr/bin/supervisord' '-c' '/data/supervisord.conf'`

but i changed this with Portainer, dunno how to add this to the run command.

![grafik](https://user-images.githubusercontent.com/14855001/48959584-a5abc300-ef66-11e8-85f8-5e2df1965d29.png)

now i could start octoprint.

after that i added the system command to start/stop the webcam by adding this lines in the config.yml
```
system:
  actions:
  - action: streamon
    command: supervisorctl start mjpeg-streamer
    confirm: false
    name: Start Webcam
  - action: streamoff
    command: supervisorctl stop mjpeg-streamer
    confirm: false
    name: Stop Webcam
temperature:
  profiles:
  - bed: 70
    extruder: 210
    name: PLA
webcam:
  ffmpeg: /usr/bin/ffmpeg
  snapshot: http://127.0.0.1:8080/?action=snapshot
  stream: /webcam/?action=stream
  watermark: false
```

after the docker restart the quick system menu showed up:
![grafik](https://user-images.githubusercontent.com/14855001/48959699-6c278780-ef67-11e8-8e7d-20f2a0ba24c1.png)
